version: "3"

services:
  registry:
    image: registry:2 # ghcr.io/sqing33/registry
    container_name: registry
    restart: always
    ports:
      - 1500:5000
    volumes:
      - /vol3/1000/Docker镜像仓库:/var/lib/registry
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true # 启用删除功能
    networks:
      - registry

  registry-ui:
    image: quiq/registry-ui # ghcr.io/sqing33/registry-ui
    container_name: registry-ui
    restart: always
    volumes:
      - /vol1/1000/Docker/registry/config.yml:/opt/config.yml:ro
    ports:
      - 1501:8000
    networks:
      - registry

  docker-image-sync:
    build: .
    container_name: docker-image-sync-to-registry
    privileged: true # 需要特权模式来运行Docker
    environment:
      - REGISTRY_URL=http://registry:5000 # 本地私有仓库的URL
      - CRON_SCHEDULE=0 4 * * * # 每天凌晨4点执行
      - SYNC_ON_START=true # 容器启动时立即同步
      - TARGET_ARCH=linux/amd64,linux/arm64 # 目标架构
      - REMOVE_LIBRARY_PREFIX_ON_LOCAL=true # 是否移除本地镜像的library/前缀
      - MAX_PAGES_PER_CATEGORY=1 # 控制 Python 脚本爬取的页数
      - CRAWL_AFTER_CUSTOM_IMAGES=false # 拉取custom_images镜像列表之后是否继续爬取DockerHub
    volumes:
      - ./custom_images.txt:/app/custom_images.txt:ro # 挂载自定义镜像列表文件（可选）
    restart: unless-stopped
    networks:
      - registry

networks:
  registry:
    name: registry
